# .bash_profile

# Override the terminal string
#if [ "${KDE_FULL_SESSION}" == "true" ]; then
#    TERM="konsole-256color"
#else
#    TERM="xterm-256color"
#fi
#TERM="xterm-256color"


# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

#export CLICOLOR=1
