#!/bin/sh
# .profile

# TODO: Stick CDPATH in here somewhere

[[ -r "${HOME}/.lib/myenv.sh" ]] && source ${HOME}/.lib/myenv.sh || echo "Can't find MyENV libs"

ISHELL=0
case "$-" in *i*) ISHELL=1;; esac
export ISHELL

__detect_distro

if [[ "${DISTRO}" == "Ubuntu" ]] && [[ "${DISTREL}" -lt "12" ]]; then
	export TERM="xterm"
fi
__ENVIRO=""
export __ENVIRO

# Only run this stuff if we are an interactive shell
if [[ "${ISHELL}" -eq 1 ]]; then
	
	# Source the global profile
	if [ -r "/etc/profile" ]; then
		source /etc/profile
	fi
    
    # Source terminal color settings and functions
    [[ -r ~/.etc/term_colors.profile ]] && source ~/.etc/term_colors.profile
    
    if [[ "${DISTRO}" == "OSX" ]]; then
        GITPROMPT='/opt/local/share/doc/git-core/contrib/completion/git-prompt.sh'
    else
        GITPROMPT='/usr/share/git-core/contrib/completion/git-prompt.sh'
    fi
    GITPROMPT_FALLBACK="${HOME}/.lib/git-prompt.sh"
	[[ -r "${GITPROMPT}" ]] && source ${GITPROMPT} || [ -r "${GITPROMPT_FALLBACK}" ] && source ${GITPROMPT_FALLBACK} || __echo "Git prompt broken, incomplete MyENV"

    GREP_COLOR="1;33;40"
    LESS="-QR"
    GIT_PS1_SHOWDIRTYSTATE=1
    GIT_PS1_SHOWSTASHSTATE=1
    GIT_PS1_SHOWUNTRACKEDFILES=1
    PROMPT_COMMAND='export __retval="$?"'

	# /opt/local/bin/gdircolors is provided by 'coreutils' in macports
    if [[ "${DISTRO}" == "OSX" ]] && [[ -x "/opt/local/bin/gdircolors" ]]; then
		eval "$(gdircolors -b ${HOME}/.dir_colors)"
    elif [[ -x "/usr/bin/dircolors" ]]; then
		eval "$(dircolors -b ${HOME}/.dir_colors)"
    fi
    
    export GREP_COLOR LESS PS1 GIT_PS1_SHOWDIRTYSTATE GIT_PS1_SHOWSTASHSTATE GIT_PS1_SHOWUNTRACKEDFILES
fi

